// gen-redact-patterns generates pkg/session/redact_patterns_gen.go from the
// gitleaks default ruleset (https://github.com/gitleaks/gitleaks, MIT licensed).
//
// The gitleaks version used is pinned in gitleaks-version.txt next to this file
// so that plain `go generate` is deterministic and reproducible. Run with
// -update to resolve the latest gitleaks release, regenerate, and rewrite the
// pin — the whole effect of an update lands as a reviewable git diff.
//
// Usage:
//
//	go run ./tools/gen-redact-patterns            # regenerate from the pinned tag
//	go run ./tools/gen-redact-patterns -update    # bump pin to latest release and regenerate
//	go run ./tools/gen-redact-patterns -local f   # generate from a local gitleaks.toml
package main

import (
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

// skippedRules are gitleaks rules deliberately excluded from redaction, with the
// reason. Redaction has a different error profile than scanning: an over-broad
// match mangles the saved transcript, and rules that depend on gitleaks' entropy
// or keyword post-filters over-match when reduced to their regex alone.
var skippedRules = map[string]string{
	"generic-api-key":  "keyword-proximity + entropy rule; regex alone over-redacts ordinary prose",
	"curl-auth-header": "matches across whole curl invocations (multi-line); too broad and costly for transcript redaction",
	"curl-auth-user":   "matches across whole curl invocations (multi-line); too broad and costly for transcript redaction",
	"jwt-base64":       "secret spread across alternating named groups; group replacement would leave partial token fragments",
	"pkcs12-file":      "path-based rule with no content regex",
}

type gitleaksRule struct {
	ID          string   `toml:"id"`
	Description string   `toml:"description"`
	Regex       string   `toml:"regex"`
	SecretGroup int      `toml:"secretGroup"`
	Keywords    []string `toml:"keywords"`
}

type gitleaksConfig struct {
	Rules []gitleaksRule `toml:"rules"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-redact-patterns:", err)
		os.Exit(1)
	}
}

func run() error {
	update := flag.Bool("update", false, "resolve latest gitleaks release, rewrite the pin, and regenerate")
	local := flag.String("local", "", "generate from a local gitleaks.toml instead of downloading")
	out := flag.String("out", "", "output file (default pkg/session/redact_patterns_gen.go relative to module root)")
	flag.Parse()

	toolDir, err := selfDir()
	if err != nil {
		return err
	}
	versionFile := filepath.Join(toolDir, "gitleaks-version.txt")

	tag, err := readPin(versionFile)
	if err != nil {
		return err
	}
	if *update {
		latest, lerr := latestReleaseTag()
		if lerr != nil {
			return fmt.Errorf("resolving latest gitleaks release: %w", lerr)
		}
		if latest != tag {
			fmt.Printf("updating gitleaks pin: %s -> %s\n", tag, latest)
			tag = latest
			if werr := os.WriteFile(versionFile, []byte(tag+"\n"), 0o644); werr != nil {
				return fmt.Errorf("rewriting pin file: %w", werr)
			}
		} else {
			fmt.Printf("gitleaks pin already at latest (%s)\n", tag)
		}
	}

	var source []byte
	sourceName := ""
	if *local != "" {
		source, err = os.ReadFile(*local)
		if err != nil {
			return fmt.Errorf("reading local gitleaks.toml: %w", err)
		}
		sourceName = *local
	} else {
		url := fmt.Sprintf("https://raw.githubusercontent.com/gitleaks/gitleaks/%s/config/gitleaks.toml", tag)
		source, err = download(url)
		if err != nil {
			return err
		}
		sourceName = url
	}
	sum := sha256.Sum256(source)

	var cfg gitleaksConfig
	if err := toml.Unmarshal(source, &cfg); err != nil {
		return fmt.Errorf("parsing gitleaks.toml: %w", err)
	}
	if len(cfg.Rules) == 0 {
		return fmt.Errorf("no rules found in %s", sourceName)
	}

	outPath := *out
	if outPath == "" {
		outPath = filepath.Join(toolDir, "..", "..", "pkg", "session", "redact_patterns_gen.go")
	}

	code, included, skipped, err := generate(cfg.Rules, tag, fmt.Sprintf("%x", sum))
	if err != nil {
		return err
	}
	if err := os.WriteFile(outPath, code, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	fmt.Printf("wrote %s: %d rules included, %d skipped (gitleaks %s)\n", outPath, included, skipped, tag)
	return nil
}

// generate renders the Go source for the generated pattern table. Rules are
// sorted by ID so output is deterministic for a given gitleaks version.
func generate(rules []gitleaksRule, tag, sum string) ([]byte, int, int, error) {
	sorted := make([]gitleaksRule, len(rules))
	copy(sorted, rules)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-redact-patterns; DO NOT EDIT.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Source: gitleaks %s config/gitleaks.toml (sha256 %s)\n", tag, sum)
	b.WriteString("//\n")
	b.WriteString("// The regular expressions below are derived from the gitleaks project\n")
	b.WriteString("// (https://github.com/gitleaks/gitleaks), which is licensed under the MIT\n")
	b.WriteString("// License, Copyright (c) 2019 Zachary Rice:\n")
	b.WriteString("//\n")
	b.WriteString("// Permission is hereby granted, free of charge, to any person obtaining a copy\n")
	b.WriteString("// of this software and associated documentation files (the \"Software\"), to deal\n")
	b.WriteString("// in the Software without restriction, including without limitation the rights\n")
	b.WriteString("// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n")
	b.WriteString("// copies of the Software, and to permit persons to whom the Software is\n")
	b.WriteString("// furnished to do so, subject to the following conditions: The above copyright\n")
	b.WriteString("// notice and this permission notice shall be included in all copies or\n")
	b.WriteString("// substantial portions of the Software.\n")
	b.WriteString("package session\n\n")
	b.WriteString("import \"regexp\"\n\n")
	b.WriteString("// generatedPatterns mirrors the gitleaks default ruleset, minus the rules the\n")
	b.WriteString("// generator's skip-list excludes (generic/entropy-dependent rules that over-match\n")
	b.WriteString("// when reduced to their regex alone). See tools/gen-redact-patterns/main.go.\n")
	b.WriteString("var generatedPatterns = []redactPattern{\n")

	included, skipped := 0, 0
	for _, r := range sorted {
		if reason, skip := skippedRules[r.ID]; skip {
			fmt.Fprintf(&b, "\t// skipped %s: %s\n", r.ID, reason)
			skipped++
			continue
		}
		if r.Regex == "" {
			fmt.Fprintf(&b, "\t// skipped %s: rule has no regex\n", r.ID)
			skipped++
			continue
		}
		re, err := regexp.Compile(r.Regex)
		if err != nil {
			fmt.Fprintf(&b, "\t// skipped %s: regex does not compile as Go RE2: %v\n", r.ID, err)
			skipped++
			continue
		}
		// Gitleaks convention: the secret is capture group 1 when the rule has
		// capture groups (context rules), the whole match otherwise. A rule can
		// override with secretGroup.
		group := r.SecretGroup
		if group == 0 && re.NumSubexp() >= 1 {
			group = 1
		}
		label := strings.ToUpper(strings.ReplaceAll(r.ID, "-", "_"))
		// Keywords are gitleaks' regex prefilter: the (expensive) regex only runs
		// when one of these literals appears in the lowercased content. Without
		// this, 200+ regexes per document is pathologically slow on big sessions.
		keywords := make([]string, 0, len(r.Keywords))
		for _, kw := range r.Keywords {
			if kw = strings.ToLower(strings.TrimSpace(kw)); kw != "" {
				keywords = append(keywords, kw)
			}
		}
		sort.Strings(keywords)
		var kwLit strings.Builder
		kwLit.WriteString("[]string{")
		for i, kw := range keywords {
			if i > 0 {
				kwLit.WriteString(", ")
			}
			kwLit.WriteString(strconv.Quote(kw))
		}
		kwLit.WriteString("}")
		fmt.Fprintf(&b, "\t{re: regexp.MustCompile(%s), label: %q, group: %d, keywords: %s},\n",
			strconv.Quote(r.Regex), label, group, kwLit.String())
		included++
	}
	b.WriteString("}\n")
	return []byte(b.String()), included, skipped, nil
}

func readPin(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading pin file %s: %w", path, err)
	}
	tag := strings.TrimSpace(string(data))
	if tag == "" {
		return "", fmt.Errorf("pin file %s is empty", path)
	}
	return tag, nil
}

func latestReleaseTag() (string, error) {
	body, err := download("https://api.github.com/repos/gitleaks/gitleaks/releases/latest")
	if err != nil {
		return "", err
	}
	var release struct {
		TagName string `json:"tag_name"`
	}
	if err := json.Unmarshal(body, &release); err != nil {
		return "", err
	}
	if release.TagName == "" {
		return "", fmt.Errorf("release response has no tag_name")
	}
	return release.TagName, nil
}

func download(url string) ([]byte, error) {
	resp, err := http.Get(url) //nolint:gosec // fixed github.com URLs assembled from a reviewed pin
	if err != nil {
		return nil, fmt.Errorf("GET %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: HTTP %d", url, resp.StatusCode)
	}
	return io.ReadAll(resp.Body)
}

// selfDir locates this tool's source directory so the pin file and default
// output path resolve correctly regardless of the caller's working directory.
func selfDir() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("cannot determine tool source location")
	}
	return filepath.Dir(file), nil
}
